#!/bin/python3

import os
import subprocess

print("------------------------------")
print("superbarosa azure superplex")
print("------------------------------")

BAROSA_BASE_DIR = os.getcwd()
DIRS = os.listdir(BAROSA_BASE_DIR)

dirs_built = 0
for module in DIRS:
    if not os.path.isdir(module):
        continue

    main_go = os.path.join(BAROSA_BASE_DIR, module, "main.go")
    if not os.path.isfile(main_go):
        # not a go module
        continue

    print(f"Building {module} ...")
    os.chdir(os.path.join(BAROSA_BASE_DIR, module))
    build_command = f"go build -o {module} main.go"
    subprocess.run(build_command, shell=True, check=True)
    os.chdir(BAROSA_BASE_DIR)
    dirs_built += 1

print(f"Built {dirs_built} Go modules")
