# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22.4'

    - name: Barosa Azure
      run: cd backend/barosa-azure && go build -v main.go

    - name: Barosa Server
      run: cd backend/barosa-server && go build -v main.go

    - name: Barosa Screenshot
      run: cd backend/barosa-screen-capture && go build -v main.go


